% DEMRCA Test RCA on TP53 expression data.
%
% SEEALSO : kernCreate, kernCompute, rca
%
% Author: Alfredo A. Kalaitzis, 2011

% RCA

addpath(genpath('~/mlprojects/matlab/general/'))
addpath(genpath('~/mlprojects/gp/matlab/'));
gpToolboxes;

load DellaGatta_data_for_RCAdemo.mat
idx_top500 = sortIndex(1:500);
dtaTP53 = exprs_tp53_RMA(:, idx_top500);
dtaTMXF = exprs_null_RMA(:, idx_top500);

% For every time-point, subtract mean expression along all genes.
% Should not be standardized; might need to look at signal variance in the
% context of all signals variances.
dtaTP53 = dtaTP53 - repmat(mean(dtaTP53,2), 1, size(dtaTP53,2));
dtaTMXF = dtaTMXF - repmat(mean(dtaTMXF,2), 1, size(dtaTMXF,2));

tTrue = [0:20:240 0 20 40 60 120 180 240]';
kern = kernCreate(tTrue, 'rbf');
%%
typDiff = 20; % Typical time difference between samples.
kern.inverseWidth = 1/(typDiff*typDiff); % Characteristic inverse-width.
% First kernel assumes the two profiles are generated by the same process;
% the second, that the two profiles are generated independently.
K_comb = kernCompute(kern, tTrue) + eye(20)*0.01;
K_ind = blkdiag(K_comb(1:13,1:13),K_comb(14:end,14:end));
figure(1); imshow(K_comb); figure(2); imshow(K_ind);

%%
Y = [dtaTP53' dtaTMXF']; % Concatenate profiles of both conditions.
YtY = Y'*Y; % Gram matrix. Full rank.
