% DEMRCA Test RCA on TP53 expression data.
%
% SEEALSO : kernCreate, kernCompute, rca, compareROC
%
% Author: Alfredo A. Kalaitzis, 2011

% RCA

addpath(genpath('~/mlprojects/matlab/general/'))
addpath(genpath('~/mlprojects/gp/matlab/'));
addpath(genpath('~/mlprojects/gprege/matlab/'));
gpToolboxes;

randn('seed', 1e7)
rand('seed', 1e7)

load DellaGatta_data_for_RCAdemo.mat
m=4;
tTrue = [0:20:240 0 20 40 60 120 180 240]';
kern = kernCreate(tTrue, 'rbf');
typDiff = 20; % Typical time difference between samples.
kern.inverseWidth = 1/(typDiff*typDiff); % Characteristic inverse-width.
% First kernel assumes the two profiles are generated by the same process;
% the second, that the two profiles are generated independently.
K_comb = kernCompute(kern, tTrue) + eye(20)*0.01;
%K_ind = blkdiag(K_comb(1:13,1:13),K_comb(14:end,14:end));
figure(3), %clf;

% for k=0:20;
% idx_top = sortIndex( ((k*1000)+1) : ((k*1000)+1000) );
% idx_top = sortIndex(1:500);
idx_top = 1:length(exprs_tp53_RMA);
% Concatenate profiles of both conditions.
Y = [exprs_tp53_RMA(:, idx_top); exprs_null_RMA(:, idx_top)];
[~, N] = size(Y);
% For every time-point, subtract mean expression along all genes.
%Y = (Y - repmat(mean(Y,2),1,N)) ./ repmat(std(Y,0,2),1,N);

[X,D] = rca(Y, K_comb);
%[X_,D_] = rca(Y, K_ind);

figure(1), clf,
subplot(5,2,1), imshow(K_comb), title('Combined RBF-kernels')
line([0 20.5],[13.5 13.5],'color','w'), line([13.5 13.5],[0 20.5],'color','w')
%subplot(5,2,2), imshow(K_ind), title('Independent RBF-kernels')
%line([0 20.5],[13.5 13.5],'color','w'), line([13.5 13.5],[0 20.5],'color','w')
%subplot(5,2,3:4);
%bar([D D_]), title('Generalised eigenvalue spectrum'),
%legend('Combined','Independent'), xlim([0 21])
% Plot eigvecs, combined
subplot(5,2,5:6);
plot(X(:,1:3)), ylim([-5 5]), xlim([0 21])
title('Generalised eigenvectors (combined case)')
% Plot eigvecs, independent
%subplot(5,2,7:8);
%plot(X_(:,1:20)), ylim([-5 5]), xlim([0 21])
%title('Generalised eigenvectors (independent case)')

i=1;
subplot(5,2,9:10);
plot([0 27], [0 0], '--', 'color', [.8 .8 .8]), hold on,
plot((1:13), autosc(Y(1:13,i)'), '.-b', [14:17 20 23 26], autosc(Y(14:end,i)'), '.-r'),
xlim([0 27])
Xproj = X(:,1:m)*X(:,1:m)'*Y(:,i); Xproj = Xproj/(D(1)); %./(ones(20,1)*std(Xproj));
plot((1:13), Xproj(1:13), '.-k', [14:17 20 23 26], Xproj(14:end)', '.-k'),
hold off, title('Joint-profile projection onto principal gen''d eigenvectors')

Y = [exprs_tp53_RMA; exprs_null_RMA];
proj = X(:,1:m)'*Y;
dists = (sum(proj.^2,1))';
% [RCArank, RCArank_idx] = sort(dists,'descend');
figure(2), clf, %compareROC(dists, DGatta_labels_byTSNI);
hold on, auc=compareROC(dists, DGatta_labels_byTSNItop100);
%{
% figure(2), clf, hold on, axis equal,
% plot(proj(1,:), proj(2,:), '.','markersize',1 )
% colormap('gray'); cmap = flipud(colormap);
% dists = dists/max(dists);
% for j = 1:size(Y,2)
%     text(proj(1,j), proj(2,j), num2str(j), ...
%         'color', cmap(ceil(dists(j)*length(cmap)),:), ...
%         'fontsize', 1.5+dists(j)*20);
%     
% end
% x1proj = X(:,1)'*Y;
%}

% figure(3), hold on, plot(k, auc, 'Xg');
% end



